### ISSUE TITLE
Rename package "stage"

### ISSUE THREAD

**Issue by aminemzid** [aminemzid/PlanningDesGardesMedicales#6]
Renommer le package "stage" en "gardeplan".

**Comment by mzid** [comment]
Je ne vois pas de package qui s'appelle stage, c'est déjà fait je pense

**Comment by aminemzid** [comment]
URL du repo : https://github.com/aminemzid/PlanningDesGardesMedicales

**Comment by mzid** [comment]
Done

**Comment by aminemzid** [comment]
Il reste à modifier le "groupe Id" dans le pom.xml !

Une fois le travail terminé, tu devrais me réassigner le ticket pour validation pour que que je le ferme, c'est toujours le créateur du ticket qui le ferme et non pas celui qui l'a traité.

**Comment by mzid** [comment]
pom.xml modifié

**Comment by aminemzid** [comment]
Très bien, ticket validé, tu peux passer aux autres ?
